### PR TITLE
PR for Raise eslint error levels and fix errors in code issue

### LINKED ISSUE #1333: [JS] Raise eslint error levels and fix errors in code
These are really important to lock down the app and improve stability. `eslint` should be able to raise alarms and prevent people shipping many obvious bugs. Pull requests with these bugs will not be able to be merged.

Because changing these touches many files in the codebase, it's important to make changes and file a PR in a single day. Many other developers are working and it is easier and cleaner to do these quickly.

You can read documentation on the individual errors here: https://eslint.org/docs/rules/

Do these one at a time, opening a new PR for each one.

1. In `.eslintrc.json` increase these from warning (1) to error (2)
2. Run `npm run lint:errors` and fix all errors.

- [x]  "no-undef": 1,
- [ ]    "no-unused-vars": 1,

If you are using VSCode then I recommend installing [TypeScript Hero](https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero) which includes "Sort and organize your imports (sort and remove unused)". This works on normal .js and .jsx files as well as .ts
It will instantly clean up imports and remove unused.

Unused variables are grayed out in VSCode which makes it very easy to spot and fix.

- [ ]    "no-dupe-keys": 1,
- [ ]    "no-empty": 1,
- [ ]    "no-extra-boolean-cast": 1,
- [ ]    "no-constant-condition": 1,
- [ ]    "no-prototype-builtins": 1,
- [ ]    "no-underscore-dangle": 1,
- [ ]    "no-unreachable": 1,
- [ ]    "no-useless-escape": 1,

### PR DESCRIPTION
**Pull request by vijayant123**
Initial commit

Fix #1333

### CODE REVIEW

**Comment by vijayant123** [comment]
The first commit for this huge task. It fixes errors of the first item in the list of eslint rules - no-unused-vars. This PR would be complete when all the items in the list get converted to corresponding commits. I will keep rebasing my branch to master branch so as to keep getting updated changes from others. That way the PR would be ready for merge whenever it is complete.

Dear @crucialfelix sir, please review this initial commit and notify me of any errors or changes needed. Currently the warnings count stands at 1818 after this commit.

File: app/actions/authActions.js [hunk 1]
```diff
@@ -95,9 +94,12 @@ export function forgot_password(data, navigation = undefined) {
   };
 }
 
+// eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/actions/authActions.js]: These 3 disables are appropriate and correct I think.

The other way to do it is to comment out the variable

`(/* dispatch */) => {` 

That way it is readable, we know what the unused argument is. Someone may need the dispatch in the future. (It's a redux-thunk handler)

File: app/actions/authActions.js [hunk 2]
```diff
@@ -107,24 +109,29 @@ export function sendEmail(navigation = undefined) {
...
+          throw err;
+        })
+    );
   };
 }
 export function setAccessDenied(data, params, path, navigation = undefined) {
   return dispatch => {
     postRequest('public_accessDenied', data, params)
       .then(res => {
+        // eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/actions/authActions.js]: Just comment out (but don't delete) the next line since it really isn't used.

File: app/actions/authActions.js [hunk 3]
```diff
@@ -107,24 +109,29 @@ export function sendEmail(navigation = undefined) {
...
         const { statusText } = res;
         updateRoute(path, navigation || dispatch);
         // NotificationManager.success(statusText, i18n.t('label.success'), 5000);
       })
+      // eslint-disable-next-line no-unused-vars
       .catch(error => {
```
Comment (crucialfelix) [inline app/actions/authActions.js]: `console.log(error);`   is best. We strip out all console.logs at build time, but we definitely should be posting them for debugging work.

File: app/actions/donateAction.js [hunk 4]
```diff
@@ -31,11 +30,13 @@ export function fillCard() {
 }
 
 export function attachCardToCostumer(paymentMethod) {
+  // eslint-disable-next-line no-unused-vars
   return dispatch => {
     let request = postAuthenticatedRequest('stripe_paymentMethod_attach', {
       paymentMethod,
       version: 'v1.3'
     });
+    // eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/actions/donateAction.js]: Here I think you can replace `response` with `()` (no args)

File: app/actions/signupActions.js [hunk 5]
```diff
@@ -56,7 +56,9 @@ export function signUp(
       i18n.t('label.error'),
       5000
     );
+    // eslint-disable-next-line no-unused-vars
     return dispatch => {
+      // eslint-disable-next-line no-unused-vars
       return new Promise(function(resolve, reject) {
```
Comment (crucialfelix) [inline app/actions/signupActions.js]: Better to just omit the unused arg `function(resolve) {`

File: app/actions/types.js [hunk 6]
```diff
@@ -1,6 +1,7 @@
 const LOGIN = 'LOGIN';
 const LOGOUT = 'LOGOUT';
 const REGISTER = 'REGISTER';
+// eslint-disable-next-line no-unused-vars
 const SET_CURRENT_USER = 'SET_CURRENT_USER';
```
Comment (crucialfelix) [inline app/actions/types.js]: comment it out instead. It's code that was never used.

File: app/actions/updateUserProfile.js [hunk 7]
```diff
@@ -112,6 +112,7 @@ export function orderPlantProject(data, params) {
     return new Promise(function(resolve, reject) {
       postAuthenticatedRequest('plantProject_position', data, params)
         .then(res => {
+          // eslint-disable-next-line no-unused-vars
           const { statusText } = res;
```
Comment (crucialfelix) [inline app/actions/updateUserProfile.js]: Just delete the line.

File: app/components/AboutUs/LicenseInfoList.native.js [hunk 8]
```diff
@@ -40,6 +37,7 @@ export default class LicenseInfoList extends Component {
       <View style={styles.content}>
         <TouchableItem
           onPress={() => {
+            // eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/components/AboutUs/LicenseInfoList.native.js]: uncomment the `console.log`

File: app/components/AboutUs/LicenseInfoList.native.js [hunk 9]
```diff
@@ -61,6 +60,7 @@ export default class LicenseInfoList extends Component {
     );
   };
   render() {
+    // eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/components/AboutUs/LicenseInfoList.native.js]: Definitely comment out the next line. It is doing useless work.

File: app/components/AboutUs/index.native.js [hunk 10]
```diff
@@ -13,6 +13,7 @@ const LicenseInfo = require('./LicenseInfo.json');
 class AboutUs extends Component {
   render() {
     const version = DeviceInfo.getReadableVersion();
+    // eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/components/AboutUs/index.native.js]: Comment out the code instead. Unused.

File: app/components/App/TreeCounter.native.js [hunk 11]
```diff
@@ -32,6 +30,7 @@ class App extends Component {
   }
 }
 
+// eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/components/App/TreeCounter.native.js]: `(/* state */) =>`  is good style here. That is readable — we know what the unused arg name is.

File: app/components/Challenge/challengeList.native.js [hunk 12]
```diff
@@ -15,6 +15,7 @@ class ChallengeList extends Component {
       />
     );
   }
+  // eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/components/Challenge/challengeList.native.js]: `item => item.id.toString()`

File: app/components/Common/ArrowButton.js [hunk 13]
```diff
@@ -16,6 +16,7 @@ class ArrowButton extends Component {
   }
 
   render() {
+    // eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/components/Common/ArrowButton.js]: This isn't used so you can comment it out. It looks like someone was trying to get it to rotate but it isn't working or finished.

File: app/components/Common/Button/FollowLabelButton.native.js [hunk 14]
```diff
@@ -6,6 +6,7 @@ import PropTypes from 'prop-types';
 import i18n from '../../../locales/i18n';
 
 const FollowLabelButton = ({
+  // eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/components/Common/Button/FollowLabelButton.native.js]: It's really not used, you can remove it. Now in this case there may be some code using `<FollowLabelButton isLoggedIn={ ...} ... />`  Search for usages.

File: app/components/Competition/Tabs/mine.native.js [hunk 15]
```diff
@@ -22,6 +18,7 @@ import imageUpload from '../../../assets/images/icons/upload_image.png';
 import ImagePicker from 'react-native-image-picker';
 
 let Form = t.form.Form;
+// eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/components/Competition/Tabs/mine.native.js]: You can comment out the whole getCompFormLayoutTemplate function. It's not used nor exported.

File: app/components/EditUserProfile/index.js [hunk 16]
```diff
@@ -74,7 +70,7 @@ export default class EditUserProfile extends React.Component {
     }
   };
 
-  mergeProjectImages(newPlantProjectImages, oldPlantProjectImages = []) {
+  mergeProjectImages(newPlantProjectImages) {
```
Comment (crucialfelix) [inline app/components/EditUserProfile/index.js]: I see you found the two usages of mergeProjectImage that do pass in an array for the second argument. Apparently that isn't used.

Looks good!

File: app/components/NDVI/Legend.native.js [hunk 17]
```diff
@@ -14,6 +14,7 @@ const LegendInfo = props => {
   );
 };
 
+// eslint-disable-next-line no-unused-vars
 const Legend = props => {
```
Comment (crucialfelix) [inline app/components/NDVI/Legend.native.js]: React functional style would be to destructure the props, but with an empty `{}` (no props required)

```js
const Legend = ({}) => {
   // etc
};
```
Does that makes sense?  It's a common idiom.

File: app/components/Payment/Gateways/Paypal.js [hunk 18]
```diff
@@ -1,3 +1,4 @@
+// eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/components/Payment/Gateways/Paypal.js]: What is next line? React? That is used.

File: app/components/Payment/Gateways/StripeCC.native.js [hunk 19]
```diff
@@ -51,6 +51,7 @@ export default class StripeCC extends Component {
         cvc: this.state.params.cvc
       };
       this.props.setLoading(true);
+      // eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/components/Payment/Gateways/StripeCC.native.js]: Just remove `const token = `

so it's 

```js
stripe.createTokenWithCard(params).then(token => 
```

File: app/components/Payment/Stripe/Element.js [hunk 20]
```diff
@@ -8,11 +8,17 @@ const noop = () => {};
 
 const _extractOptions = props => {
   const {
+    // eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/components/Payment/Stripe/Element.js]: If they aren't used then comment them out. Leave them there so we know what we aren't using.

File: app/components/PlantProjects/PlantProjectDetails.js [hunk 21]
```diff
@@ -22,6 +21,7 @@ class PlantProjectDetails extends React.Component {
       homepageCaption,
       plantProjectImages,
       videoUrl,
+      // eslint-disable-next-line no-unused-vars
```
Comment (crucialfelix) [inline app/components/PlantProjects/PlantProjectDetails.js]: Doesn't look used. comment it out.

**Comment by crucialfelix** [comment]
I think I didn't make it clear enough in the issue: Let's complete and merge this PR with just fixing these undefineds.  We want to move fast and get it into develop.

Then do another PR for other fixes.

I didn't leave comments for all of them, I ran out of time.  Thanks!

**Comment by crucialfelix** [comment]
Hi @vijayant123 - Let me know what your schedule and plan is for this. Maybe you are working on a different issue or project right now. Is there anything I can do to help?

File: app/components/NDVI/Legend.native.js (hunk 17 above)
Comment (vijayant123) [reply app/components/NDVI/Legend.native.js]: It makes sense.

File: app/components/Payment/Gateways/Paypal.js (hunk 18 above)
Comment (vijayant123) [reply app/components/Payment/Gateways/Paypal.js]: There's a unique issue here:
Look at these lines:
Line 2:
/* global paypal */
Line 47:
let paypal = window.paypal;

The eslint error is with line 2 "'paypal' is defined but never used. eslint(no-unused-vars)". The issue here is that line 47 assigns a local variable with the property paypal of the window object. Thus the object that is actually accessed is window. This causes us to change line 2 to:

/* global paypal */

But this launches a newer error from eslint for line 2 "'window' is already defined as a built-in global variable. eslint(no-redeclare)". This leaves us to remove the line 2 altogether. If you agree on this then I'll commit the change where lines 1 and 2 are removed from this file.

**Comment by vijayant123** [comment]
> Hi @vijayant123 - Let me know what your schedule and plan is for this. Maybe you are working on a different issue or project right now. Is there anything I can do to help?

Hey, I have resolved most of your comments and pushed a commit with all the changes following rules you suggested. Sorry this got delayed, I didn't get much time in the last few days. You can review the changes and merge this PR if you need to before I finish with other eslint rules. For the remaining eslint rules, I intent to work on and finish them all day tomorrow. The current warnings count stands at 1806 after the latest commits.

**Comment by crucialfelix** [comment]
Great, thanks!  I want to merge this PR with just these fixes.  You can do the rest of the changes in a separate PR (or several - as you see fit).

**Comment by crucialfelix** [comment]
I just realized that you have this PR set to merge into master. We need to do all work and PRs to merge into develop.  master is for releases.

I rebased your work and the two commits I added into this PR: #1514

**Comment by vijayant123** [comment]
I will rebase to your branch "origin/eslint-fixes" to include your two commits into my branch and thus into this PR (You will not need to create another PR then). I suggest you wait a few hours for my next commit fixing all the rest of eslint errors. There's 383 errors remaining after converting all the remaining eslint rules to errors. Could you please fix the eslint commands in package.json so that it covers all the relevant codebase folders when run using npm?

**Comment by crucialfelix** [comment]
OK, you should handle it, that's better.

Merge into develop.

Here's another annoyance: because your branch is called eslint-fixes and not features/eslint-fixes, the circle CI is not running. It only runs for feature/ develop/ master/ hotfix/

**Comment by crucialfelix** [comment]
I do think you should NOT include more fixes for the other error types. Let's merge this PR as soon as we can. Then continue with another PR.

It will make review and testing a lot easier.

**Comment by vijayant123** [comment]
Hey @crucialfelix, all eslint fixes are done. The current warning count stands at 1823. I have disabled no-console rule from eslint:recommended for the time being. As you already stated that console logs are disabled at production runtime, so I have set this rule to warning in .eslintrc.json.

Following rules are also mainly disabled in the code base (as they are heavily used) so please review them:
1. https://eslint.org/docs/rules/no-useless-escape
2. https://eslint.org/docs/rules/no-underscore-dangle

File: app/server/parserLiformToTcomb.js [hunk 22]
```diff
@@ -28,8 +28,8 @@ export default function parseJsonToTcomb(liformSchemaJson, config, validator) {
 
     for (let propertyKey in properties) {
       let newEnum = {};
-      if (properties.hasOwnProperty(propertyKey)) {
-        if (properties[propertyKey].hasOwnProperty('enum')) {
+      if (properties.propertyKey) {
```
Comment (crucialfelix) [inline app/server/parserLiformToTcomb.js]: Whoops, bug!  propertyKey is a variable

`properties[propertyKey]` is not the same as `properties. propertyKey`

File: app/server/parserLiformToTcomb.js [hunk 23]
```diff
@@ -48,15 +48,15 @@ export default function parseJsonToTcomb(liformSchemaJson, config, validator) {
       fields: {}
     };
     for (let propertyKey in properties) {
-      if (properties.hasOwnProperty(propertyKey)) {
+      if (properties.propertyKey) {
```
Comment (crucialfelix) [inline app/server/parserLiformToTcomb.js]: here too

File: web/widgets/common/native-shim.js [hunk 24]
```diff
@@ -22,7 +22,7 @@
     window.customElements === undefined ||
     // The webcomponentsjs custom elements polyfill doesn't require
     // ES2015-compatible construction (`super()` or `Reflect.construct`).
-    window.customElements.hasOwnProperty('polyfillWrapFlushCallback')
+    window.customElements['polyfillWrapFlushCallback']
```
Comment (crucialfelix) [inline web/widgets/common/native-shim.js]: Don't change this: it is a shim written by Polymer. 

They are checking for capability: does window.customElements have 'polyfillWrapFlushCallback' but they are not checking the truthyness of what is returned (although I'm sure it's true).

File: web/widgets/progressbar/native-shim.js [hunk 25]
```diff
@@ -22,7 +22,7 @@
     window.customElements === undefined ||
     // The webcomponentsjs custom elements polyfill doesn't require
     // ES2015-compatible construction (`super()` or `Reflect.construct`).
-    window.customElements.hasOwnProperty('polyfillWrapFlushCallback')
+    window.customElements['polyfillWrapFlushCallback']
```
Comment (crucialfelix) [inline web/widgets/progressbar/native-shim.js]: Don't change this one either. 3rd party code by people smarter than us.

File: app/server/parserLiformToTcomb.js (hunk 22 above)
Comment (vijayant123) [reply app/server/parserLiformToTcomb.js]: Thanks for pointing this out!

File: app/server/parserLiformToTcomb.js (hunk 23 above)
Comment (vijayant123) [reply app/server/parserLiformToTcomb.js]: Thanks!

**Comment by vijayant123** [comment]
Fixed many issues. All your reported fixes have been implemented. Regards.

**Comment by vijayant123** [comment]
Thank you for approving the PR @crucialfelix . I have enabled you as a contributor on my repository so that you can make any last minute commits, if needed, during the merge of this PR.

File: app/components/PublicTreeCounter/TreecounterHeader.native.js [hunk 26]
```diff
@@ -42,7 +42,6 @@ const TreecounterHeader = ({
           {showFollow ? (
             <FollowLabelButton
               isSubscribed={isUserFollowerBool}
```
Comment (mahmed0715) [inline app/components/PublicTreeCounter/TreecounterHeader.native.js]: @crucialfelix is this okay?

Comment (crucialfelix) [reply app/components/PublicTreeCounter/TreecounterHeader.native.js]: Yes, because `FollowLabelButton` does not take `isLoggedIn` anymore (it wasn't using it).
