### PR TITLE
Competition Details all enrollments error

### LINKED ISSUE #1949: TypeError in MainActivity
## Error in Plant-for-the-Planet App

**TypeError** in **MainActivity**
undefined is not an object (evaluating 'c.allEnrollments.map')

[View on Bugsnag](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e469a691664570019caa2b4?event_id=5e469a690055f621e01f0000&i=gh&m=ci)

## Stacktrace

    app/components/Competition/CompetitionFull.native.js:469 - value

[View full stacktrace](https://app.bugsnag.com/plant-for-the-planet/plant-for-the-planet-app/errors/5e469a691664570019caa2b4?event_id=5e469a690055f621e01f0000&i=gh&m=ci)

*Created automatically via Bugsnag*

### PR DESCRIPTION
**Pull request by ankitecd**
Fixes #1949 

Changes in this pull request:
- added flag to existence of allEnrollments in competitionDetails

@norbertschuler

### CODE REVIEW

File: app/containers/TargetContainer/index.js [hunk 1]
```diff
@@ -18,6 +18,11 @@ class TargetContainer extends React.Component {
     this.onSubmitTarget = this.onSubmitTarget.bind(this);
   }
   onSubmitTarget = () => {
+    console.log(
```
Comment (norbertschuler) [inline app/containers/TargetContainer/index.js]: please either use debug or remove logging again.
